### ISSUE TITLE
in `Bot.edit_message_mediag`, for some reason `media` is a optional kwarg, which is clearly wrong. Changing that is breaking, so putting on the v14 milestone.

### ISSUE THREAD

**Issue by jerry971** [aarontreinish/TextNow-Chat-App#4]
in `Bot.edit_message_mediag`, for some reason `media` is a optional kwarg, which is clearly wrong. Changing that is breaking, so putting on the v14 milestone.

We could think about expanding `test_official` to parse the offical docs in order to check such things.

__Originally posted by @Bibo-Joshi in https://github.com/python-telegram-bot/python-telegram-bot/issues/2367__

**Comment by jerry971** [comment]
- [Lionjj88
](https://t.me/instagram)

**Comment by Bibo-Joshi** [comment]
@jerry971 you seem to have a liking for copy-pasting issues from python-telegram-bot/python-telegram-bot (also #3 and #2) is there a particular reason to do this

a) at all
b) on this repo
c) with mentioning the original author?

If not, I kindly ask you to stop.
